apiVersion: apps/v1
kind: Deployment
metadata:
    name: pol-proxy
    labels:
        app: pol-proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pol-proxy
    template:
        metadata:
            labels:
                app: pol-proxy
        spec:
            containers:
                - name: pol-proxy
                  image: polhub/pol-proxy:latest
                  ports:
                      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: pol-proxy
spec:
    type: ClusterIP
    ports:
        - port: 8080
          targetPort: 8080
    selector:
        app: pol-proxy
